version: '3'

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file: backend/.env
    environment:
      NODE_ENV: production
    ports:
      - '5000:5000'

  storefront:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - '5001:80'
